

CONST_STOP_ALGORITHM = 2000
CONST_STOP_ALGORITHM_BY_MEAN_HEALTH = 0.0001
CONST_NUMB_GETTING_INFO = 10



CONST_TYPE_NEUTRAL = 'neutral'
CONST_TYPE_PATHOGENIC = 'pathogenic'
CONST_TYPE_LETHAL = 'lethal'

CONST_STOP_ALGORITHM = 200
PRECISION = 0.0001
CONST_NUMB_GETTING_INFO = 10
